name: CI
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  golangci-lint:
    defaults:
      run:
        shell: bash
        working-directory: app
    permissions:
      contents: read
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./app/golangci-lint.mod
      - name: Run lint
        run: go tool -modfile=golangci-lint.mod golangci-lint run
  go-std-test:
    defaults:
      run:
        shell: bash
        working-directory: app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./app/go.mod
      - name: Run test
        run: go test -v ./...
