on:
  push:
    branches:
      - main

jobs:
  exec-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: haskell-actions/setup@7909071ceec0344debcc968c6c7a96a52e8dd0d7 # v2.8.1
        with:
          ghc-version: 9.2.8
          cabal-version: 3.6.2
      - id: analyze
        run: |
          ANALYZE_RESULT=$(go run analyzer/cmd/cli/main.go)
          echo "ANALYZE_RESULT=$ANALYZE_RESULT" >> "$GITHUB_OUTPUT"
        working-directory: app
      - id: notify
        env: 
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        run: echo '${{ steps.analyze.outputs.ANALYZE_RESULT }}' | cabal run
        working-directory: app/notifier
