on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - id: analyze
        run: go run analyzer/cmd/cli/main.go | xargs -Ianalyzec_result_value echo "ANALYZE_RESULT=analyzec_result_value"  >> "$GITHUB_OUTPUT"
        working-directory: app
      - run: echo ${{ steps.analyze.outputs.ANALYZE_RESULT }}
